export const languageAliases = {
    js: 'javascript',
    ts: 'typescript',
    jsx: 'javascript',
    tsx: 'typescript',
    html: 'xml',
    html5: 'xml',
    md: 'markdown',
    yml: 'yaml',
    py: 'python',
    rb: 'ruby',
    kt: 'kotlin',
    rs: 'rust',
    sc: 'scala',
};
