import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [{
    type: 'autogenerated',
    dirName: 'learn'
  }],
  examplesSidebar: [{
    type: 'autogenerated',
    dirName: 'examples'
  }],
  videosSidebar: [{
    type: 'autogenerated',
    dirName: 'videos'
  }],
  referenceSidebar: [{
    type: 'autogenerated',
    dirName: 'reference'
  }],
};

export default sidebars;
