import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  referenceSidebar: [{
    type: 'autogenerated',
    dirName: 'reference'
  }],
  learnSidebar: [{
    type: 'autogenerated',
    dirName: 'learn'
  }],

  examplesSidebar: [{
    type: 'autogenerated',
    dirName: 'examples'
  }],
};

export default sidebars;
